version: '3.1'
services:
  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init/:/docker-entrypoint-initdb.d
      - ./docker/postgres/data/:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    depends_on:
      - db